# Generated by Django 5.0.2 on 2024-11-20 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appeal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='murojat',
            options={'ordering': ['-created_at']},
        ),
    ]
