# Generated by Django 5.0.2 on 2024-11-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_file'),
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='files',
            field=models.ManyToManyField(blank=True, to='common.file'),
        ),
        migrations.AlterField(
            model_name='pages',
            name='images',
            field=models.ManyToManyField(blank=True, to='common.image'),
        ),
    ]
