# Generated by Django 5.0.2 on 2024-11-19 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='video_file',
        ),
    ]
