# Generated by Django 5.0.2 on 2024-11-20 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('university', '0004_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.image'),
        ),
    ]
